### ISSUE TITLE
Automatically get language from browser

### ISSUE THREAD

**Issue by ricardovsilva** [ruby/TryRuby#12]
I have one sugestion. We can automatically get the language that browser provide to us. A little javascript code can do the trick.
My idea is:
1 - Has cache data with language selected?
1.1 - Yes, use selected language.
1.2 - No, use browser language

What do you think? Can I add this functionality?

**Comment by ricardovsilva** [comment]
Forget, you're already doing that. But, for some reason, it's not working (I'm running my own fork). When I enter the page, my language is get as "pt-br" (I'm using firefox developer console). But page still shown in english.

**Comment by easydatawarehousing** [comment]
Strange. I will look into this and releasing the code later this week. Bit busy right now.

Ivo

**Comment by easydatawarehousing** [comment]
Hi Ricardo,

I have looked at you translation. Looks great ! Some parts I can read, since I know what it says in English. And I ran a bunch of texts through google translate. I think you really captured the style and spirit in which the original was written by _why.

Found a couple of minor issues, see below. And the solution to the auto-detect problem. In source/javascripts/try_ruby.rb, line 117 should be: case browserlang.downcase

Do you think we can add portugese (pt) to the auto detect languages?

Best regards,
Ivo

Note that translation remarks are just suggestions. Your call what to do with them :)
1   You can translate welcome, if you want

5   You can use a common Brazilian name instead of Jimmy

9   NoMethodError: undefined method `reverse' for 40

15  I guess that ticket is a Brazilian word ?

20  NoMethodError: undefined method `poem' for main

23  Translate 'books' to 'livros' ?

25  Translate the book titles ?

30  Translate 'time' ?

34  Translation contains English: If you don’t get the title of this chapter.
      No user feedback line

37  English in the title: Waves Its Hat. Is that okay?

40  Typo: SHakespeare -> Shakespeare

45  English text: You loaded some data of the internet

52  Typo: eesta -> esta

54  NoMethodError: undefined method `-' for nil

55  NoMethodError: undefined method `-' for nil

56  NoMethodError: undefined method `-' for nil

**Comment by ricardovsilva** [comment]
I'm going to verify these error points. About portuguese language (you mean portuguese from any country right? Like Portugal, Angola, and others?
If is that, yes, we can add pt too. Portuguese is very similar in all countries that has it as native language.

**Comment by ricardovsilva** [comment]
Ivo, I didn't get the point.
For example:

> 1 You can translate welcome, if you want
> 5 You can use a common Brazilian name instead of Jimmy

They are pointed in file 1 and 50?

And what is the welcome? Because file 1 is already translated.

**Comment by easydatawarehousing** [comment]
About Portuguese from other countries: yep exactly what I meant. So I guess we can add 'pt' to the auto-select list.
1. I meant the word welcome in the code: 3.times do print 'Welcome ' end
2. For the Dutch translation I used 'Jantje' instead of Jimmy. In Spanish we used 'Juan'. So maybe you can use a common Brazilian name here.
   This name is indeed used in several lessons.

**Comment by easydatawarehousing** [comment]
Hi,

It's definitely been too long since I worked on Tryruby. Forgot all the finer details. So you are absolutely right. I was looking up numbers in the json file, I should have looked up the numbers of the markdown files (1 and 25 in this case).
And the 'welcome' text can't be translated without modifying the code. So forget that.

I saw you replaced Jimmy with Ricardo (excellent choice) and addressed all other issues. It is all working perfectly. Last 2 remarks I have: in markdown file 380 the feedback string are in English. And don't forget to edit the README.md file, replace all names with you own. All credits to you :)

I look forward to seeing your PR and will release your translation asap.

Best regards,
Ivo

**Comment by ricardovsilva** [comment]
The README.md file was the ~/README.md or ~/translations/pt-br/README.md ? If was root file, it was already updated :)
Also, translated the backup in file 380.

**Comment by easydatawarehousing** [comment]
Cool. I meant ~/translations/pt-br/README.md

**Comment by ricardovsilva** [comment]
I took example from other translations. README.md updated too.

**Comment by easydatawarehousing** [comment]
Okay, great. Merging your PR now. I'll release it this weekend and let you when it's live.
Thanks,
Ivo

**Comment by easydatawarehousing** [comment]
And it live. I've added your name to the about page. Let me know if you find any remaining issues.
Thanks again for all your work.
