### ISSUE TITLE
Standing in line: most negative or decimal numbers not accepted

### ISSUE THREAD

**Issue by duianto** [ruby/TryRuby#38]
On the page: https://ruby.github.io/TryRuby/

The exercise: `Standing in Line`

Asks for an additional number to the list: `[12, 47, 35]`

But it doesn't accept most negative or most decimal numbers.
ex: `[12, 47, 35, -1]` or `[12, 47, 35, 1.5]`

the same message is shown as if no additional number had been added:
>Try adding a fourth number to the list

These are accepted:
`[12, 47, 35, -0]`, `[12, 37, 35, -0.0]` and even `[12, 37, 35, 2.0]`

the negative sign and fraction isn't shown in the output window:
`[12, 47, 35, 0]`, `[12, 47, 35, 0]`, and `[12, 47, 35, 2]`

If it's difficult or not that important to check for negative or decimal numbers, then a simpler solution could be to request a positive whole number:

Before:
>Try adding a number to this list: type a comma after 35 followed by a number. The space is optional.

After:
>Try adding a positive whole number to this list: type a comma after 35 followed by a positive whole number. The space is optional.

**Comment by easydatawarehousing** [comment]
Good point. I have changed the regex so that it also works with floats and negative numbers. It is still possible to 'trick' the test, for instance using exponential notation. But I think it is good enough for its purpose.

The fact that rounded floats are converted to integers is due to the implementation of opal. Numbers are javascript numbers, not ruby objects. Not a major issue I think.
